name: CI - Build and Push Strapi Image to ECR
on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_ref: ${{ steps.set-output.outputs.image_ref }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Get short sha
        id: sha
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        id: build-push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/strapi:latest
            ${{ steps.login-ecr.outputs.registry }}/strapi:${{ steps.sha.outputs.SHORT_SHA }}

      - name: Set image ref output
        id: set-output
        run: |
          IMAGE_REF=${{ steps.login-ecr.outputs.registry }}/strapi:${{ steps.sha.outputs.SHORT_SHA }}
          echo "image_ref=$IMAGE_REF" >> $GITHUB_OUTPUT
